name: Deploy Multi Sites

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy each site from CSV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_TEAM: ${{ secrets.NETLIFY_TEAM }}
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
        run: |
          CSV_FILE="${{ vars.SITES_CSV || 'sites.csv' }}"
          PUBLIC_ROOT="${{ vars.PUBLIC_ROOT || 'Public' }}"
          while IFS=',' read -r folder site_name domain sitemap
          do
            # пропускаем заголовок
            if [ "$folder" = "folder" ]; then continue; fi

            echo "=== Deploying ${site_name} (${domain}) from ${PUBLIC_ROOT}/${folder}"

            # Если сайт уже создан в Netlify — можно указать --site <site_id|name>
            netlify deploy \
              --auth="$NETLIFY_AUTH_TOKEN" \
              --dir="${PUBLIC_ROOT}/${folder}" \
              --site="$site_name" \
              --prod

            # Пингуем IndexNow (предполагается файл https://domain/INDEXNOWKEY.txt)
            # Отправляем sitemap, если указан (иначе просто главную)
            if [ -n "$sitemap" ]; then
              URL="https://${domain}/${sitemap}"
            else
              URL="https://${domain}/"
            fi

            curl -s -H 'Content-Type: application/json' \
              -d "{\"host\":\"${domain}\",
                   \"key\":\"${INDEXNOW_KEY}\",
                   \"keyLocation\":\"https://${domain}/${INDEXNOW_KEY}.txt\",
                   \"urlList\":[\"${URL}\"]}" \
              https://api.indexnow.org/submit

            echo "IndexNow ping sent for ${domain} -> ${URL}"
          done < "$CSV_FILE"
