name: Deploy Multi Sites

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Locate files (debug)
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          find . -maxdepth 3 -type f -name "sites.csv" -print

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Netlify CLI
        run: |
          npm i -g netlify-cli
          netlify --version

      - name: Deploy each site from CSV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_TEAM: ${{ secrets.NETLIFY_TEAM }}
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
          # Можно переопределить в Settings → Secrets and variables → Actions → Variables
          SITES_CSV: ${{ vars.SITES_CSV }}
          PUBLIC_ROOT: ${{ vars.PUBLIC_ROOT }}
        run: |
          set -euo pipefail

          # 1) Пути по умолчанию
          CSV_FILE="${SITES_CSV:-PT/sites.csv}"
          PUBLIC_DIR="${PUBLIC_ROOT:-.}"

          CSV_PATH="$GITHUB_WORKSPACE/$CSV_FILE"
          echo "Using CSV: $CSV_PATH"
          if [[ ! -f "$CSV_PATH" ]]; then
            echo "ERROR: CSV not found at $CSV_PATH"
            ls -la "$GITHUB_WORKSPACE"
            exit 1
          fi

          # 2) Читаем CSV: folder,site_name,domain,sitemap
          #    Пропускаем заголовок и строки-комменты (# ...)
          #    Удаляем \r на случай CRLF
          while IFS=',' read -r folder site_name domain sitemap; do
            # trim CR
            folder="${folder%%[$'\r\n']}"
            site_name="${site_name%%[$'\r\n']}"
            domain="${domain%%[$'\r\n']}"
            sitemap="${sitemap%%[$'\r\n']}"

            # пропускаем пустые, заголовок и комментарии
            [[ -z "${folder:-}" ]] && continue
            [[ "$folder" == "folder" ]] && continue
            [[ "$folder" =~ ^# ]] && continue

            SRC_DIR="${PUBLIC_DIR}/${folder}"
            echo "=== Deploy: site_name='${site_name}' domain='${domain}' src='${SRC_DIR}'"

            if [[ ! -d "$SRC_DIR" ]]; then
              echo "WARN: Source dir not found: $SRC_DIR — пропускаю"
              continue
            fi

            # 3) Prod‑деплой на Netlify
            # Если у тебя есть конкретный site-id, можно заменить --site "$site_name" на --site "<site-id>"
            netlify deploy \
              --auth="$NETLIFY_AUTH_TOKEN" \
              --dir="$SRC_DIR" \
              --site="$site_name" \
              --prod

            # 4) Пинг IndexNow (если есть домен)
            if [[ -n "${domain:-}" ]]; then
              if [[ -n "${sitemap:-}" ]]; then
                URL="https://${domain}/${sitemap}"
              else
                URL="https://${domain}/"
              fi

              echo "Pinging IndexNow for ${domain} -> ${URL}"
              curl -s -H 'Content-Type: application/json' \
                -d "{\"host\":\"${domain}\",
                     \"key\":\"${INDEXNOW_KEY}\",
                     \"keyLocation\":\"https://${domain}/${INDEXNOW_KEY}.txt\",
                     \"urlList\":[\"${URL}\"]}" \
                https://api.indexnow.org/submit || true
            fi

            echo "=== Done: ${site_name} (${domain})"
          done < "$CSV_PATH"
