name: Deploy Multi Sites

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Locate sites.csv
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          find . -maxdepth 3 -name "sites.csv" -print


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy each site from CSV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_TEAM_ID: ${{ secrets.NETLIFY_TEAM }}
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
        run: |
          # берём имя CSV из переменной, иначе по умолчанию sites.csv
          CSV_FILE="${{ vars.SITES_CSV }}"
          if [ -z "$CSV_FILE" ]; then CSV_FILE="PT/sites.csv"; fi

          # абсолютный путь
          CSV_PATH="$GITHUB_WORKSPACE/$CSV_FILE"
          echo "Using CSV: $CSV_PATH"

          # проверка наличия
          if [ ! -f "$CSV_PATH" ]; then
            echo "ERROR: CSV not found at $CSV_PATH"
            ls -la "$GITHUB_WORKSPACE"
            exit 1
          fi

          # корень для папок сайтов
          PUBLIC_ROOT="${{ vars.PUBLIC_ROOT }}"
          if [ -z "$PUBLIC_ROOT" ]; then PUBLIC_ROOT="."; fi

          while IFS=',' read -r folder site_name domain sitemap
          do
            if [ "$folder" = "folder" ]; then continue; fi
            echo "=== Deploying ${site_name} (${domain}) from ${PUBLIC_ROOT}/${folder}"

            netlify deploy \
              --auth="$NETLIFY_AUTH_TOKEN" \
              --dir="${PUBLIC_ROOT}/${folder}" \
              --site="$site_name" \
              --prod

            if [ -n "$sitemap" ]; then
              URL="https://${domain}/${sitemap}"
            else
              URL="https://${domain}/"
            fi

            curl -s -H 'Content-Type: application/json' \
              -d "{\"host\":\"${domain}\",
                   \"key\":\"${INDEXNOW_KEY}\",
                   \"keyLocation\":\"https://${domain}/${INDEXNOW_KEY}.txt\",
                   \"urlList\":[\"${URL}\"]}" \
              https://api.indexnow.org/submit

            echo "IndexNow ping sent for ${domain} -> ${URL}"
          done < "$CSV_PATH"


            echo "IndexNow ping sent for ${domain} -> ${URL}"
          done < "$CSV_FILE"
